server:
  port: 9009

spring:
  datasource:
    url: jdbc:mysql://db:3306/localspringbootdb
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   show-sql: true
   properties:
    hibernate:
      ddl-auto: update 
  main:
   allow-bean-definition-overriding: true
  
      
         
      